name: Counter Deploy
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: [self-hosted, linux, CPSC334]
    container: ubuntu:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python
        run: |
          apt-get update
          apt-get install -y python3 python3-pip
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y dpkg-dev
      
      - name: Build Debian package
        run: |
          make build-deb
      
      # SCP the Debian package to counterVM
      - name: Copy Debian package to counterVM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "counter-v2.0.0.deb"
          target: "/tmp"
      
      # Install the package on counterVM
      - name: Install package on counterVM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            sudo dpkg -i /tmp/counter-v2.0.0.deb
            sudo systemctl restart counter.service
