name: Counter Package and Lint (Self-Hosted)
on: [push]
jobs:
  build-package:
    runs-on: [self-hosted, linux, CPSC334]
    container: ubuntu:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python
        run: |
          apt-get update
          apt-get install -y python3 python3-pip
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y dpkg-dev lintian
      - name: Build Debian package
        run: |
          make build-deb
      - name: Upload Debian package artifact
        uses: actions/upload-artifact@v4
        with:
          name: counter-package
          path: counter-v2.0.0.deb
          retention-days: 7
  
  lint-deb:
    runs-on: [self-hosted, linux, CPSC334]
    container: ubuntu:latest
    needs: build-package
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install lintian
        run: |
          apt-get update
          apt-get install -y lintian
      - name: Download Debian package artifact
        uses: actions/download-artifact@v4
        with:
          name: counter-package
      - name: Modify Makefile for lintian
        run: |
          sed -i 's/lintian counter-v2.0.0.deb/-lintian counter-v2.0.0.deb/g' Makefile
      - name: Lint Debian package
        run: |
          make lint-deb
