name: Counter Build and Test (Self-Hosted)
on: [push]
jobs:
  build:
    runs-on: [self-hosted, linux, CPSC334]
    container: ubuntu:latest
    timeout-minutes: 2
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python environment
        run: |
          apt-get update
          apt-get install -y python3 python3-pip python3-venv
      - name: Create virtual environment
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
      - name: Build project
        run: |
          . .venv/bin/activate
          make build
  
  test:
    runs-on: [self-hosted, linux, CPSC334]
    container: ubuntu:latest
    timeout-minutes: 2
    needs: build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python environment
        run: |
          apt-get update
          apt-get install -y python3 python3-pip python3-venv
      - name: Create virtual environment and install dependencies
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run tests
        run: |
          . .venv/bin/activate
          make test
